stickers = ['CAADBAADiwADS2nuEDLWeAeRE5xUFgQ', 'CAADBAADiwADS2nuEDLWeAeRE5xUFgQ', 'CAADAgAD-wMAAonq5Qf_IUE4P2Nx8BYE',
            'CAADAgADRgIAArw4kSEw6k_GwgrbIBYE', 'CAADAgADYE8AAuCjggdAmHb61DCAKhYE', 'CAADAgADoAADQGd0EQ_esa8RPC6wFgQ',
            'CAADAgADOgADDGqfEryj_Ag7ERQxFgQ', 'CAADAgADOwEAAooSqg5WysIGqZgJaBYE', 'CAADBAADqAIAAndomgI9rZLPszJOHhYE',
            'CAADAgADLgADta-yDsYWj1wM_dbNFgQ', 'CAADAgAD3AEAAsdjXBXJxWy2y75mcBYE', 'CAADAgADpAcAAhhC7gg3H3BYAAGdoAcWBA',
            'CAADAgADCQcAAvoLtgh2uosCnUnKExYE', 'CAADBAADngQAAigeHQrjdPzZa7N2MBYE', 'CAADAgADHhUAAulVBRiWhozHlVLv8RYE',
            'CAADAgADLAQAAujW4hJqAXfxdLIc2hYE', 'CAADAgADBAADkp8eEavc7j2rScUkFgQ', 'CAADAgADLgIAAlN4dBMb5dFNPj-VpBYE',
            'CAADAgADEgEAAoynlwh9E0m0KFSv7xYE', 'CAADAgADGQADwDZPE9BDgPYgVxRLFgQ', 'CAADAgADhAADAcY0Gj1eWsynbrtNFgQ',
            'CAADBAADAQEAAqApMBbElCNwxosjnxYE', 'CAADAgADDQAD3yU9GXGp4ot5VjK0FgQ', 'CAADAgADRioAAktqAwABpztxBIMFr9gWBA',
            'CAADAgADSgADVapNCuqYBNaFb0W_FgQ', 'CAADAgADNAADobczCLITe84J5k4QFgQ', 'CAADAgADaAkAAtA90gjUawy5doNRJRYE']

TOKEN = '946867453:AAFY657srK8t5bRuquYyCuuoo9ZxPXjGflE'

my_user_id = 227190186
my_user_name = '@MeriDK'

chat_id = -1001416070393

fw_id = 674929718

sasha_sticker = 'CAADAgADygEAAj-xbANVvn2dRBGc8xYE'
